# Generated by Django 4.2 on 2025-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Stores the type of event occured', max_length=20)),
                ('source', models.CharField(help_text='Stores the source through which event originated', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Stores the time at which event occured')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
